"""new table

Revision ID: 10da70bdc395
Revises: cc662d956bbb
Create Date: 2022-09-09 10:00:17.139855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10da70bdc395'
down_revision = 'cc662d956bbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
