"""add new table

Revision ID: 2542698b468e
Revises: 4885681ee8f9
Create Date: 2022-09-08 14:25:52.557839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2542698b468e'
down_revision = '4885681ee8f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('need', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_needs_id'), 'team_needs', ['id'], unique=False)
    op.drop_column('team_ideas', 'needed_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_ideas', sa.Column('needed_skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_team_needs_id'), table_name='team_needs')
    op.drop_table('team_needs')
    # ### end Alembic commands ###
