"""Table Stack

Revision ID: 305a3594e383
Revises: 10da70bdc395
Create Date: 2022-09-10 17:51:28.686662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '305a3594e383'
down_revision = '10da70bdc395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stacks_id'), 'stacks', ['id'], unique=False)
    op.create_index(op.f('ix_stacks_name'), 'stacks', ['name'], unique=True)
    op.create_table('user_stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stacks_id'), 'user_stacks', ['id'], unique=False)
    op.drop_index('ix_skills_id', table_name='skills')
    op.drop_index('ix_skills_name', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='skills_pkey')
    )
    op.create_index('ix_skills_name', 'skills', ['name'], unique=False)
    op.create_index('ix_skills_id', 'skills', ['id'], unique=False)
    op.drop_index(op.f('ix_user_stacks_id'), table_name='user_stacks')
    op.drop_table('user_stacks')
    op.drop_index(op.f('ix_stacks_name'), table_name='stacks')
    op.drop_index(op.f('ix_stacks_id'), table_name='stacks')
    op.drop_table('stacks')
    # ### end Alembic commands ###
