"""MAde

Revision ID: 4885681ee8f9
Revises: 99dc4e3a7164
Create Date: 2022-09-07 22:55:16.977688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4885681ee8f9'
down_revision = '99dc4e3a7164'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
