"""new table

Revision ID: 4a62cdd274e3
Revises: 305a3594e383
Create Date: 2022-09-10 18:09:01.313846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a62cdd274e3'
down_revision = '305a3594e383'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
