"""aha

Revision ID: 62c315da4b33
Revises: bc7ca55bff71
Create Date: 2022-09-07 21:59:40.657723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c315da4b33'
down_revision = 'bc7ca55bff71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
