"""ajde pls

Revision ID: 99dc4e3a7164
Revises: 62c315da4b33
Create Date: 2022-09-07 22:06:13.724363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dc4e3a7164'
down_revision = '62c315da4b33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
