"""New table finished

Revision ID: d9dee0ee5366
Revises: 2542698b468e
Create Date: 2022-09-08 14:40:00.828356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9dee0ee5366'
down_revision = '2542698b468e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
