"""add data

Revision ID: f2922a8f7fc0
Revises: 2fa236822110
Create Date: 2022-09-06 23:43:58.153354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2922a8f7fc0'
down_revision = '2fa236822110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('shortdesc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shortdesc')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
